version: '3.8'

services:

  mysql:
    container_name: '${CONTAINER_PREFIX_NAME}-mysql'
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    ports:
      - '3306:3306'
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - symfony-network

  php:
    container_name: '${CONTAINER_PREFIX_NAME}-php'
    build:
      context: ./php
    expose:
      - '9000'
    volumes:
      # code
      - ../app:/var/www/symfony
    networks:
      - symfony-network

  nginx:
    container_name: '${CONTAINER_PREFIX_NAME}-nginx'
    image: nginx:1.21
    ports:
      - '80:80'
    env_file:
      - .env
    volumes:
      # vhost
      - ./nginx/templates/symfony.conf.template:/etc/nginx/templates/symfony.conf.template
      # code
      - ../app:/var/www/symfony
      # logs
      - ./nginx/logs:/var/log/nginx:cached
    networks:
      - symfony-network
    depends_on:
      - php

  encore:
    container_name: '${CONTAINER_PREFIX_NAME}-encore'
    image: node:latest
    volumes:
      - ../app:/var/www/symfony
    working_dir: /var/www/symfony
    # for webpack-encore v1, "--disable-host-check" is replaced with "--firewall false"
    command: >
      sh -c "yarn install &&
             yarn encore dev-server --hot --port 9999 --host 0.0.0.0"
    ports:
      - "9999:9999"
    networks:
      - symfony-network

networks:
  symfony-network:

#Volumes
volumes:
  dbdata:
    driver: local