twig:
    form_themes: ['bootstrap_5_layout.html.twig']
    default_path: '%kernel.project_dir%/templates'

    paths:
        'templates/admin/': 'Admin'

when@test:
    twig:
        strict_variables: true

